/** VNDB short-code to sprite-class lookups for inline icons. */


export const ICON = {

  /* Language flags */
  "LANGUAGE": {
    ar: "icon-lang-ar",
    be: "icon-lang-be",
    bg: "icon-lang-bg",
    ca: "icon-lang-ca",
    ck: "icon-lang-ck",
    cs: "icon-lang-cs",
    da: "icon-lang-da",
    de: "icon-lang-de",
    el: "icon-lang-el",
    en: "icon-lang-en",
    eo: "icon-lang-eo",
    es: "icon-lang-es",
    eu: "icon-lang-eu",
    fa: "icon-lang-fa",
    fi: "icon-lang-fi",
    fr: "icon-lang-fr",
    ga: "icon-lang-ga",
    gd: "icon-lang-gd",
    he: "icon-lang-he",
    hi: "icon-lang-hi",
    hr: "icon-lang-hr",
    hu: "icon-lang-hu",
    id: "icon-lang-id",
    it: "icon-lang-it",
    iu: "icon-lang-iu",
    ja: "icon-lang-ja",
    kk: "icon-lang-kk",
    ko: "icon-lang-ko",
    la: "icon-lang-la",
    lt: "icon-lang-lt",
    lv: "icon-lang-lv",
    mk: "icon-lang-mk",
    ms: "icon-lang-ms",
    nl: "icon-lang-nl",
    no: "icon-lang-no",
    pl: "icon-lang-pl",
    "pt-br": "icon-lang-pt-br",
    "pt-pt": "icon-lang-pt-pt",
    pt: "icon-lang-pt-pt",
    ro: "icon-lang-ro",
    ru: "icon-lang-ru",
    sk: "icon-lang-sk",
    sl: "icon-lang-sl",
    sr: "icon-lang-sr",
    sv: "icon-lang-sv",
    ta: "icon-lang-ta",
    th: "icon-lang-th",
    tr: "icon-lang-tr",
    uk: "icon-lang-uk",
    ur: "icon-lang-ur",
    vi: "icon-lang-vi",
    "zh-Hans": "icon-lang-zh-Hans",
    "zh-Hant": "icon-lang-zh-Hant",
    zh: "icon-lang-zh",
  },

  /* Platforms */
  "PLATFORM": {
    and: "icon-plat-and",
    bdp: "icon-plat-bdp",
    dos: "icon-plat-dos",
    drc: "icon-plat-drc",
    dvd: "icon-plat-dvd",
    fm7: "icon-plat-fm7",
    fm8: "icon-plat-fm8",
    fmt: "icon-plat-fmt",
    gba: "icon-plat-gba",
    gbc: "icon-plat-gbc",
    ios: "icon-plat-ios",
    lin: "icon-plat-lin",
    mac: "icon-plat-mac",
    mob: "icon-plat-mob",
    msx: "icon-plat-msx",
    n3d: "icon-plat-n3d",
    nds: "icon-plat-nds",
    nes: "icon-plat-nes",
    oth: "icon-plat-oth",
    p88: "icon-plat-p88",
    p98: "icon-plat-p98",
    pce: "icon-plat-pce",
    pcf: "icon-plat-pcf",
    ps1: "icon-plat-ps1",
    ps2: "icon-plat-ps2",
    ps3: "icon-plat-ps3",
    ps4: "icon-plat-ps4",
    ps5: "icon-plat-ps5",
    psp: "icon-plat-psp",
    psv: "icon-plat-psv",
    sat: "icon-plat-sat",
    scd: "icon-plat-scd",
    sfc: "icon-plat-sfc",
    smd: "icon-plat-smd",
    swi: "icon-plat-swi",
    tdo: "icon-plat-tdo",
    vnd: "icon-plat-vnd",
    web: "icon-plat-web",
    wii: "icon-plat-wii",
    win: "icon-plat-win",
    wiu: "icon-plat-wiu",
    x1s: "icon-plat-x1s",
    x68: "icon-plat-x68",
    xb1: "icon-plat-xb1",
    xb3: "icon-plat-xb3",
    xbo: "icon-plat-xbo",
    xxs: "icon-plat-xxs",
  },

  /* Character sex (incl. "spoil" variants) */
  "CHARACTER_SEX": {
    a: "icon-char-a",
    b: "icon-char-b",
    f: "icon-char-f",
    m: "icon-char-m",
    n: "icon-char-n",
    o: "icon-char-o",
    u: "icon-char-u",
  },

  /* Release media (disk / cartridge / download / …) */
  "RELEASE_MEDIA": {
    "in":  "icon-rel-download",
    cd:    "icon-rel-disk",
    dvd:   "icon-rel-disk",
    blr:   "icon-rel-disk",
    gdr:   "icon-rel-disk",
    umd:   "icon-rel-disk",
    flp:   "icon-rel-disk",
    dc:    "icon-rel-disk",
    nod:   "icon-rel-disk",
    cas:   "icon-rel-disk",
    mem:   "icon-rel-cartridge",
    mrt:   "icon-rel-cartridge",
    otc:   "icon-rel-disk",
  },

  /* Voice acting coverage (combined classes for fill level) */
  "RELEASE_VOICED": {
    1: "icon-rel-voiced",
    2: "icon-rel-voiced icon-rel-v2",
    3: "icon-rel-voiced icon-rel-v3",
    4: "icon-rel-voiced icon-rel-v4",
  },

} as const
