"""empty message

Revision ID: 23510de7a666
Revises: 2d5057ad0a52
Create Date: 2026-05-11 22:34:11.345138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23510de7a666'
down_revision = '2d5057ad0a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('aid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aid', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
