"""empty message

Revision ID: bed0ff691e6a
Revises: 4d5c474a8bff
Create Date: 2026-05-19 13:02:44.737632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed0ff691e6a'
down_revision = '4d5c474a8bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexual', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.drop_column('sexual')

    # ### end Alembic commands ###
